# Generated by Django 5.2.7 on 2025-10-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Texcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='nombre',
        ),
    ]
