# Generated by Django 5.2.7 on 2025-11-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Texcore', '0003_materia_usuario_registro_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, help_text='Cantidad de esta materia utilizada', max_digits=10)),
                ('porcentaje_mezcla', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje en la mezcla final', max_digits=5)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Texcore.materia')),
            ],
            options={
                'verbose_name': 'Detalle de Preparación',
                'verbose_name_plural': 'Detalles de Preparación',
            },
        ),
        migrations.CreateModel(
            name='PreparacionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_preparacion', models.CharField(help_text='Código único de preparación', max_length=50, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tipo_proceso', models.CharField(choices=[('limpieza', 'Limpieza de Fibras'), ('apertura', 'Apertura de Fibras'), ('mezclado', 'Mezclado de Fibras'), ('ajuste_proporciones', 'Ajuste de Proporciones')], default='limpieza', max_length=50)),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='en_proceso', max_length=20)),
                ('tipo_tela_objetivo', models.CharField(choices=[('algodon_puro', 'Algodón Puro'), ('lana_pura', 'Lana Pura'), ('seda_pura', 'Seda Pura'), ('poliester_puro', 'Poliéster Puro'), ('algodon_poliester', 'Algodón-Poliéster (Mezcla)'), ('lana_algodon', 'Lana-Algodón (Mezcla)'), ('seda_algodon', 'Seda-Algodón (Mezcla)'), ('personalizada', 'Mezcla Personalizada')], help_text='Tipo de tela que se va a producir', max_length=50)),
                ('cantidad_obtenida', models.DecimalField(decimal_places=2, default=0.0, help_text='Cantidad final obtenida después de la preparación', max_digits=10)),
                ('unidad_medida_resultado', models.CharField(default='kg', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del proceso de preparación')),
                ('calidad_aprobada', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo si aplica')),
                ('materias_utilizadas', models.ManyToManyField(related_name='preparaciones_utilizadas', through='Texcore.DetallePreparacion', to='Texcore.materia')),
                ('usuario_preparacion', models.ForeignKey(blank=True, help_text='Operario responsable de la preparación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preparación de Materia Prima',
                'verbose_name_plural': 'Preparaciones de Materias Primas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='preparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_preparacion', to='Texcore.preparacionmateria'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepreparacion',
            unique_together={('preparacion', 'materia')},
        ),
    ]
