# Generated by Django 5.2.7 on 2025-11-12 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Texcore', '0004_detallepreparacion_preparacionmateria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepreparacion',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Detalle de Preparación', 'verbose_name_plural': 'Detalles de Preparación'},
        ),
        migrations.AlterModelOptions(
            name='preparacionmateria',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Preparación de Materia', 'verbose_name_plural': 'Preparaciones de Materias'},
        ),
        migrations.AlterUniqueTogether(
            name='detallepreparacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='calidad_aprobada',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='cantidad_obtenida',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='codigo_preparacion',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='materias_utilizadas',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='tipo_tela_objetivo',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='unidad_medida_resultado',
        ),
        migrations.RemoveField(
            model_name='preparacionmateria',
            name='usuario_preparacion',
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='equipo_utilizado',
            field=models.CharField(blank=True, help_text='Equipo o máquina utilizada', max_length=100),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humedad relativa (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='merma',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de merma (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='notas_tecnicas',
            field=models.TextField(blank=True, help_text='Notas técnicas del proceso'),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendimiento del proceso (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura del proceso (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallepreparacion',
            name='tiempo_proceso',
            field=models.IntegerField(blank=True, help_text='Tiempo de proceso en minutos', null=True),
        ),
        migrations.AddField(
            model_name='preparacionmateria',
            name='calidad_resultado',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('deficiente', 'Deficiente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preparacionmateria',
            name='cantidad_procesada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad procesada en kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='preparacionmateria',
            name='materia_prima',
            field=models.ForeignKey(help_text='Materia prima a procesar', null=True, on_delete=django.db.models.deletion.CASCADE, to='Texcore.materia'),
        ),
        migrations.AddField(
            model_name='preparacionmateria',
            name='porcentaje_mezcla',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje en la mezcla final (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='preparacionmateria',
            name='usuario_preparador',
            field=models.ForeignKey(blank=True, help_text='Usuario preparador que realizó el proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallepreparacion',
            name='preparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Texcore.preparacionmateria'),
        ),
        migrations.AlterField(
            model_name='preparacionmateria',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='preparacionmateria',
            name='tipo_proceso',
            field=models.CharField(choices=[('limpieza', 'Limpieza'), ('apertura', 'Apertura'), ('mezclado', 'Mezclado'), ('ajuste_proporciones', 'Ajuste de Proporciones')], help_text='Tipo de proceso de preparación', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('operario', 'Operario'), ('preparador', 'Preparador'), ('admin', 'Administrativo')], default='operario', max_length=20),
        ),
        migrations.RemoveField(
            model_name='detallepreparacion',
            name='cantidad_utilizada',
        ),
        migrations.RemoveField(
            model_name='detallepreparacion',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='detallepreparacion',
            name='porcentaje_mezcla',
        ),
    ]
