# Generated by Django 5.2.7 on 2025-11-26 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Texcore', '0005_alter_detallepreparacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoHilatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('cardado', 'Cardado'), ('peinado', 'Peinado'), ('hilado', 'Hilado')], help_text='Etapa del proceso de hilatura', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('cantidad_fibra_entrada', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad de fibra de entrada (kg)', max_digits=10)),
                ('cantidad_hilo_salida', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad de hilo producido (kg)', max_digits=10)),
                ('titulo_hilo', models.CharField(blank=True, help_text='Título del hilo (Ne, Nm, Tex, etc.)', max_length=50)),
                ('torsion', models.DecimalField(blank=True, decimal_places=2, help_text='Torsión del hilo (TPM - Torsiones por metro)', max_digits=6, null=True)),
                ('resistencia', models.DecimalField(blank=True, decimal_places=2, help_text='Resistencia del hilo (cN/tex)', max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del proceso de hilatura')),
                ('calidad_resultado', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('deficiente', 'Deficiente')], max_length=20, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('preparacion_origen', models.ForeignKey(blank=True, help_text='Preparación de materia prima de origen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Texcore.preparacionmateria')),
                ('usuario_operador', models.ForeignKey(blank=True, help_text='Usuario operario que realizó el proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Hilatura',
                'verbose_name_plural': 'Procesos de Hilatura',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleHilatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad_maquina', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad de la máquina (m/min)', max_digits=7, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura del proceso (°C)', max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, help_text='Humedad relativa (%)', max_digits=5, null=True)),
                ('maquina_hiladora', models.CharField(blank=True, help_text='Máquina hiladora utilizada', max_length=100)),
                ('numero_husos', models.IntegerField(blank=True, help_text='Número de husos utilizados', null=True)),
                ('velocidad_cardado', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad de cardado (m/min)', max_digits=6, null=True)),
                ('limpieza_fibras', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular')], help_text='Nivel de limpieza de fibras (Cardado)', max_length=20, null=True)),
                ('longitud_fibra_eliminada', models.DecimalField(blank=True, decimal_places=2, help_text='Longitud de fibra corta eliminada (mm)', max_digits=5, null=True)),
                ('porcentaje_impurezas_removidas', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de impurezas removidas (%)', max_digits=5, null=True)),
                ('grado_torsion', models.CharField(blank=True, choices=[('baja', 'Baja Torsión'), ('media', 'Media Torsión'), ('alta', 'Alta Torsión')], help_text='Grado de torsión aplicado', max_length=20, null=True)),
                ('uniformidad', models.DecimalField(blank=True, decimal_places=2, help_text='Uniformidad del hilo (%)', max_digits=5, null=True)),
                ('tiempo_proceso', models.IntegerField(blank=True, help_text='Tiempo de proceso en minutos', null=True)),
                ('defectos_encontrados', models.TextField(blank=True, help_text='Defectos encontrados durante el proceso')),
                ('notas_tecnicas', models.TextField(blank=True, help_text='Notas técnicas del proceso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('hilatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Texcore.procesohilatura')),
            ],
            options={
                'verbose_name': 'Detalle de Hilatura',
                'verbose_name_plural': 'Detalles de Hilatura',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
